
Due to MODULEPATH changes, the following have been reloaded:
  1) libfabric/1.10.1     2) openmpi/4.0.3     3) ucx/1.8.0

Lmod has detected the following error: The following module(s) are unknown:
"torch/1.4.0"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "torch/1.4.0"

Also make sure that all modulefiles written in TCL start with the string
#%Module



created virtual environment CPython3.8.10.final.0-64 in 2704ms
  creator CPython3Posix(dest=/localscratch/yinan.19309570.0/env, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/yinan/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
Ignoring pip: markers 'python_version < "3"' don't match your environment
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo/generic, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo/generic/numpy-1.20.0+computecanada-cp38-cp38-linux_x86_64.whl
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.0+computecanada
    Not uninstalling numpy at /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2021a/lib/python3.8/site-packages, outside environment /localscratch/yinan.19309570.0/env
    Can't uninstall 'numpy'. No files were found to uninstall.
Successfully installed numpy-1.20.0+computecanada
Ignoring pip: markers 'python_version < "3"' don't match your environment
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo/generic, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/keras-2.6.0+computecanada-py2.py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/Keras_Preprocessing-1.1.2+computecanada-py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/nltk-3.5+computecanada-py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/scikit_learn-0.22.1+computecanada-cp38-cp38-linux_x86_64.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/tensorboard-2.3.0+computecanada-py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/tensorboard_plugin_wit-1.7.0+computecanada-py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/tensorflow_gpu-2.3.0+computecanada-cp38-cp38-linux_x86_64.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/tensorflow_estimator-2.3.0+computecanada-py2.py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/tokenizers-0.5.2+computecanada-cp38-cp38-linux_x86_64.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/torchtext-0.6.0+computecanada-py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/transformers-2.5.1+computecanada-py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/pycocotools-2.0.2+computecanada-cp38-cp38-linux_x86_64.whl
Requirement already satisfied: numpy>=1.9.1 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages (from Keras_Preprocessing->-r requirements.txt (line 2)) (1.20.0+computecanada)
Requirement already satisfied: six>=1.9.0 in /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/ipykernel/2021a/lib/python3.8/site-packages (from Keras_Preprocessing->-r requirements.txt (line 2)) (1.16.0)
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/joblib-1.1.0+computecanada-py2.py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/regex-2021.7.6+computecanada-cp38-cp38-linux_x86_64.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/click-8.0.3+computecanada-py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/tqdm-4.62.0+computecanada-py2.py3-none-any.whl
Requirement already satisfied: scipy>=0.17.0 in /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2021a/lib/python3.8/site-packages (from scikit-learn==0.22.1->-r requirements.txt (line 4)) (1.7.0+computecanada)
Requirement already satisfied: setuptools>=41.0.0 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages (from tensorboard==2.3.0+computecanada->-r requirements.txt (line 5)) (46.1.3)
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/protobuf-3.19.1+computecanada-py2.py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/Markdown-3.3.4+computecanada-py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/absl_py-0.15.0+computecanada-py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/grpcio-1.41.1+computecanada-cp38-cp38-linux_x86_64.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/google_auth-1.35.0+computecanada-py2.py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/google_auth_oauthlib-0.4.6+computecanada-py2.py3-none-any.whl
Requirement already satisfied: requests<3,>=2.21.0 in /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2021a/lib/python3.8/site-packages (from tensorboard==2.3.0+computecanada->-r requirements.txt (line 5)) (2.26.0+computecanada)
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/Werkzeug-2.0.2+computecanada-py3-none-any.whl
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages (from tensorboard==2.3.0+computecanada->-r requirements.txt (line 5)) (0.34.2)
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/opt_einsum-3.3.0+computecanada-py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/google_pasta-0.2.0+computecanada-py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/gast-0.3.3+computecanada-py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/wrapt-1.12.1+computecanada-cp38-cp38-linux_x86_64.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/termcolor-1.1.0+computecanada-py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/astunparse-1.6.3+computecanada-py2.py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo/avx2/h5py-2.10.0+computecanada-cp38-cp38-linux_x86_64.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo/avx2/torch-1.10.0+computecanada-cp38-cp38-linux_x86_64.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo/generic/sentencepiece-0.1.96+computecanada-cp38-cp38-linux_x86_64.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/sacremoses-0.0.46+computecanada-py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/filelock-3.3.2+computecanada-py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/boto3-1.18.1+computecanada-py3-none-any.whl
Requirement already satisfied: cython>=0.27.3 in /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2021a/lib/python3.8/site-packages (from pycocotools==2.0.2->-r requirements.txt (line 12)) (0.29.24+computecanada)
Requirement already satisfied: matplotlib>=2.1.0 in /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2021a/lib/python3.8/site-packages (from pycocotools==2.0.2->-r requirements.txt (line 12)) (3.4.2+computecanada)
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/pyasn1_modules-0.2.8+computecanada-py2.py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/cachetools-4.2.4+computecanada-py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/rsa-4.7.2+computecanada-py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/requests_oauthlib-1.3.0+computecanada-py2.py3-none-any.whl
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2021a/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard==2.3.0+computecanada->-r requirements.txt (line 5)) (1.26.6+computecanada)
Requirement already satisfied: certifi>=2017.4.17 in /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2021a/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard==2.3.0+computecanada->-r requirements.txt (line 5)) (2021.5.30+computecanada)
Requirement already satisfied: charset-normalizer~=2.0.0; python_version >= "3" in /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2021a/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard==2.3.0+computecanada->-r requirements.txt (line 5)) (2.0.2+computecanada)
Requirement already satisfied: idna<4,>=2.5; python_version >= "3" in /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2021a/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard==2.3.0+computecanada->-r requirements.txt (line 5)) (3.2+computecanada)
Requirement already satisfied: typing-extensions in /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2021a/lib/python3.8/site-packages (from torch->torchtext==0.6.0->-r requirements.txt (line 10)) (3.10.0.0+computecanada)
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/jmespath-0.10.0+computecanada-py2.py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/botocore-1.21.1+computecanada-py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/s3transfer-0.5.0+computecanada-py3-none-any.whl
Requirement already satisfied: kiwisolver>=1.0.1 in /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2021a/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools==2.0.2->-r requirements.txt (line 12)) (1.3.1+computecanada)
Requirement already satisfied: pillow>=6.2.0 in /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2021a/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools==2.0.2->-r requirements.txt (line 12)) (8.3.1+computecanada)
Requirement already satisfied: cycler>=0.10 in /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2021a/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools==2.0.2->-r requirements.txt (line 12)) (0.10.0+computecanada)
Requirement already satisfied: python-dateutil>=2.7 in /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/ipykernel/2021a/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools==2.0.2->-r requirements.txt (line 12)) (2.8.1)
Requirement already satisfied: pyparsing>=2.2.1 in /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2021a/lib/python3.8/site-packages (from matplotlib>=2.1.0->pycocotools==2.0.2->-r requirements.txt (line 12)) (2.4.7+computecanada)
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/pyasn1-0.4.8+computecanada-py2.py3-none-any.whl
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/oauthlib-3.1.1+computecanada-py2.py3-none-any.whl
ERROR: tensorflow-gpu 2.3.0+computecanada has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.20.0+computecanada which is incompatible.
ERROR: tensorflow-gpu 2.3.0+computecanada has requirement scipy==1.4.1, but you'll have scipy 1.7.0+computecanada which is incompatible.
Installing collected packages: Keras, Keras-Preprocessing, joblib, regex, click, tqdm, nltk, scikit-learn, protobuf, markdown, absl-py, grpcio, pyasn1, pyasn1-modules, cachetools, rsa, google-auth, oauthlib, requests-oauthlib, google-auth-oauthlib, tensorboard-plugin-wit, werkzeug, tensorboard, opt-einsum, google-pasta, gast, tensorflow-estimator, wrapt, termcolor, astunparse, h5py, tensorflow-gpu, tokenizers, torch, sentencepiece, torchtext, sacremoses, filelock, jmespath, botocore, s3transfer, boto3, transformers, pycocotools
Successfully installed Keras-2.6.0+computecanada Keras-Preprocessing-1.1.2+computecanada absl-py-0.15.0+computecanada astunparse-1.6.3+computecanada boto3-1.18.1+computecanada botocore-1.21.1+computecanada cachetools-4.2.4+computecanada click-8.0.3+computecanada filelock-3.3.2+computecanada gast-0.3.3+computecanada google-auth-1.35.0+computecanada google-auth-oauthlib-0.4.6+computecanada google-pasta-0.2.0+computecanada grpcio-1.41.1+computecanada h5py-2.10.0+computecanada jmespath-0.10.0+computecanada joblib-1.1.0+computecanada markdown-3.3.4+computecanada nltk-3.5+computecanada oauthlib-3.1.1+computecanada opt-einsum-3.3.0+computecanada protobuf-3.19.1+computecanada pyasn1-0.4.8+computecanada pyasn1-modules-0.2.8+computecanada pycocotools-2.0.2+computecanada regex-2021.7.6+computecanada requests-oauthlib-1.3.0+computecanada rsa-4.7.2+computecanada s3transfer-0.5.0+computecanada sacremoses-0.0.46+computecanada scikit-learn-0.22.1+computecanada sentencepiece-0.1.96+computecanada tensorboard-2.3.0+computecanada tensorboard-plugin-wit-1.7.0+computecanada tensorflow-estimator-2.3.0+computecanada tensorflow-gpu-2.3.0+computecanada termcolor-1.1.0+computecanada tokenizers-0.5.2+computecanada torch-1.10.0+computecanada torchtext-0.6.0+computecanada tqdm-4.62.0+computecanada transformers-2.5.1+computecanada werkzeug-2.0.2+computecanada wrapt-1.12.1+computecanada
Starting Task
2021-11-15 23:06:32.490819: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
terminate called after throwing an instance of 'c10::CUDAOutOfMemoryError'
  what():  CUDA out of memory. Tried to allocate 48.00 MiB (GPU 0; 31.75 GiB total capacity; 3.80 GiB already allocated; 31.00 MiB free; 3.87 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception raised from malloc at /tmp/coulombc/pytorch_build_2021-11-09_14-57-01/avx2/python3.8/pytorch/c10/cuda/CUDACachingAllocator.cpp:513 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x55 (0x2b5878c3f905 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x295bf (0x2b58149ca5bf in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x2a2c5 (0x2b58149cb2c5 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x2a7d2 (0x2b58149cb7d2 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #4: at::native::empty_cuda(c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0xef (0x2b585f976bcf in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x31766da (0x2b585fac56da in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x31b1412 (0x2b585fb00412 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #7: at::TensorIteratorBase::allocate_or_resize_outputs() + 0x386 (0x2b585368de26 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)

/var/spool/slurmd/job19309570/slurm_script: line 22: 23200 Aborted                 (core dumped) python xlnet_cv.py --ml 512 --bs 8 --epochs 50 --lr $SLURM_ARRAY_TASK_ID --es 1
2021-11-15 23:06:57.957343: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
terminate called after throwing an instance of 'c10::CUDAOutOfMemoryError'
  what():  CUDA out of memory. Tried to allocate 48.00 MiB (GPU 0; 31.75 GiB total capacity; 3.80 GiB already allocated; 31.00 MiB free; 3.87 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception raised from malloc at /tmp/coulombc/pytorch_build_2021-11-09_14-57-01/avx2/python3.8/pytorch/c10/cuda/CUDACachingAllocator.cpp:513 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x55 (0x2aba19b8c905 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x295bf (0x2aba19b2e5bf in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x2a2c5 (0x2aba19b2f2c5 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x2a7d2 (0x2aba19b2f7d2 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #4: at::native::empty_cuda(c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0xef (0x2aba0086fbcf in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x31766da (0x2aba009be6da in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x31b1412 (0x2aba009f9412 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #7: at::TensorIteratorBase::allocate_or_resize_outputs() + 0x386 (0x2ab9f4586e26 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)

/var/spool/slurmd/job19309570/slurm_script: line 23: 23254 Aborted                 (core dumped) python xlnet_cv.py --ml 512 --bs 8 --epochs 50 --lr $SLURM_ARRAY_TASK_ID --es 2
2021-11-15 23:07:22.482724: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
terminate called after throwing an instance of 'c10::CUDAOutOfMemoryError'
  what():  CUDA out of memory. Tried to allocate 48.00 MiB (GPU 0; 31.75 GiB total capacity; 3.80 GiB already allocated; 31.00 MiB free; 3.87 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception raised from malloc at /tmp/coulombc/pytorch_build_2021-11-09_14-57-01/avx2/python3.8/pytorch/c10/cuda/CUDACachingAllocator.cpp:513 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x55 (0x2b65bab12905 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x295bf (0x2b65baab45bf in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x2a2c5 (0x2b65baab52c5 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x2a7d2 (0x2b65baab57d2 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #4: at::native::empty_cuda(c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0xef (0x2b65a17f5bcf in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x31766da (0x2b65a19446da in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x31b1412 (0x2b65a197f412 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #7: at::TensorIteratorBase::allocate_or_resize_outputs() + 0x386 (0x2b659550ce26 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)

/var/spool/slurmd/job19309570/slurm_script: line 24: 23297 Aborted                 (core dumped) python xlnet_cv.py --ml 512 --bs 8 --epochs 50 --lr $SLURM_ARRAY_TASK_ID --es 3
2021-11-15 23:07:47.030616: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
terminate called after throwing an instance of 'c10::CUDAOutOfMemoryError'
  what():  CUDA out of memory. Tried to allocate 48.00 MiB (GPU 0; 31.75 GiB total capacity; 3.80 GiB already allocated; 31.00 MiB free; 3.87 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception raised from malloc at /tmp/coulombc/pytorch_build_2021-11-09_14-57-01/avx2/python3.8/pytorch/c10/cuda/CUDACachingAllocator.cpp:513 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x55 (0x2b44369da905 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x295bf (0x2b443697c5bf in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x2a2c5 (0x2b443697d2c5 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x2a7d2 (0x2b443697d7d2 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #4: at::native::empty_cuda(c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0xef (0x2b441d6bdbcf in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x31766da (0x2b441d80c6da in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x31b1412 (0x2b441d847412 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #7: at::TensorIteratorBase::allocate_or_resize_outputs() + 0x386 (0x2b44113d4e26 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)

/var/spool/slurmd/job19309570/slurm_script: line 25: 23337 Aborted                 (core dumped) python xlnet_cv.py --ml 512 --bs 8 --epochs 50 --lr $SLURM_ARRAY_TASK_ID --es 4
2021-11-15 23:08:11.655945: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
terminate called after throwing an instance of 'c10::CUDAOutOfMemoryError'
  what():  CUDA out of memory. Tried to allocate 48.00 MiB (GPU 0; 31.75 GiB total capacity; 3.80 GiB already allocated; 31.00 MiB free; 3.87 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception raised from malloc at /tmp/coulombc/pytorch_build_2021-11-09_14-57-01/avx2/python3.8/pytorch/c10/cuda/CUDACachingAllocator.cpp:513 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x55 (0x2b41429a7905 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x295bf (0x2b41429495bf in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x2a2c5 (0x2b414294a2c5 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x2a7d2 (0x2b414294a7d2 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #4: at::native::empty_cuda(c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0xef (0x2b412968abcf in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x31766da (0x2b41297d96da in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x31b1412 (0x2b4129814412 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #7: at::TensorIteratorBase::allocate_or_resize_outputs() + 0x386 (0x2b411d3a1e26 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)

/var/spool/slurmd/job19309570/slurm_script: line 26: 23376 Aborted                 (core dumped) python xlnet_cv.py --ml 512 --bs 8 --epochs 50 --lr $SLURM_ARRAY_TASK_ID --es 5
2021-11-15 23:08:36.138517: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
terminate called after throwing an instance of 'c10::CUDAOutOfMemoryError'
  what():  CUDA out of memory. Tried to allocate 48.00 MiB (GPU 0; 31.75 GiB total capacity; 3.80 GiB already allocated; 31.00 MiB free; 3.87 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception raised from malloc at /tmp/coulombc/pytorch_build_2021-11-09_14-57-01/avx2/python3.8/pytorch/c10/cuda/CUDACachingAllocator.cpp:513 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x55 (0x2b5fa31dd905 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x295bf (0x2b5fa317f5bf in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x2a2c5 (0x2b5fa31802c5 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x2a7d2 (0x2b5fa31807d2 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #4: at::native::empty_cuda(c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) + 0xef (0x2b5f89ec0bcf in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x31766da (0x2b5f8a00f6da in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x31b1412 (0x2b5f8a04a412 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #7: at::TensorIteratorBase::allocate_or_resize_outputs() + 0x386 (0x2b5f7dbd7e26 in /localscratch/yinan.19309570.0/env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)

/var/spool/slurmd/job19309570/slurm_script: line 27: 23416 Aborted                 (core dumped) python xlnet_cv.py --ml 512 --bs 8 --epochs 50 --lr $SLURM_ARRAY_TASK_ID --es 6
