Unloading StdEnv/2020

Due to MODULEPATH changes, the following have been reloaded:
  1) mii/1.1.1


The following have been reloaded with a version change:
  1) python/3.8.2 => python/3.7.4

Using base prefix '/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.7.4'
New python executable in /localscratch/yinan.26042435.0/env/bin/python
Installing setuptools, pip, wheel...
done.
Ignoring pip: markers 'python_version < "3"' don't match your environment
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/generic, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Collecting numpy==1.20.0
  ERROR: Could not find a version that satisfies the requirement numpy==1.20.0 (from versions: 1.15.0+computecanada, 1.15.2+computecanada, 1.15.4+computecanada, 1.16.0+computecanada, 1.16.2+computecanada, 1.16.3+computecanada, 1.17.4+computecanada, 1.18.1+computecanada, 1.18.4+computecanada, 1.19.1+computecanada, 1.19.2+computecanada, 1.20.2+computecanada)
ERROR: No matching distribution found for numpy==1.20.0
Ignoring pip: markers 'python_version < "3"' don't match your environment
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/generic, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Collecting torch
Collecting typing-extensions (from torch)
Installing collected packages: typing-extensions, torch
Successfully installed torch-1.9.1+computecanada typing-extensions-4.0.0+computecanada
Ignoring pip: markers 'python_version < "3"' don't match your environment
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/generic, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Collecting Keras (from -r requirements.txt (line 1))
Collecting Keras_Preprocessing (from -r requirements.txt (line 2))
Collecting nltk==3.5 (from -r requirements.txt (line 3))
Collecting scikit-learn==0.22.1 (from -r requirements.txt (line 4))
Collecting tensorboard==2.3.0+computecanada (from -r requirements.txt (line 5))
Collecting tensorboard_plugin_wit==1.7.0 (from -r requirements.txt (line 6))
Collecting tensorflow_gpu==2.3.0+computecanada (from -r requirements.txt (line 7))
Collecting tensorflow_estimator==2.3.0 (from -r requirements.txt (line 8))
Collecting tokenizers==0.5.2 (from -r requirements.txt (line 9))
Collecting torchtext==0.6.0 (from -r requirements.txt (line 10))
Collecting transformers==2.5.1+computecanada (from -r requirements.txt (line 11))
Collecting urllib3==1.26.8+computecanada (from -r requirements.txt (line 12))
Requirement already satisfied: six>=1.9.0 in /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages (from Keras_Preprocessing->-r requirements.txt (line 2)) (1.12.0)
Requirement already satisfied: numpy>=1.9.1 in /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages (from Keras_Preprocessing->-r requirements.txt (line 2)) (1.16.0)
Collecting tqdm (from nltk==3.5->-r requirements.txt (line 3))
Collecting joblib (from nltk==3.5->-r requirements.txt (line 3))
Collecting regex (from nltk==3.5->-r requirements.txt (line 3))
Collecting click (from nltk==3.5->-r requirements.txt (line 3))
Requirement already satisfied: scipy>=0.17.0 in /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages (from scikit-learn==0.22.1->-r requirements.txt (line 4)) (1.2.0)
Collecting markdown>=2.6.8 (from tensorboard==2.3.0+computecanada->-r requirements.txt (line 5))
Collecting grpcio>=1.24.3 (from tensorboard==2.3.0+computecanada->-r requirements.txt (line 5))
Collecting google-auth<2,>=1.6.3 (from tensorboard==2.3.0+computecanada->-r requirements.txt (line 5))
Collecting google-auth-oauthlib<0.5,>=0.4.1 (from tensorboard==2.3.0+computecanada->-r requirements.txt (line 5))
Collecting werkzeug>=0.11.15 (from tensorboard==2.3.0+computecanada->-r requirements.txt (line 5))
Collecting protobuf>=3.6.0 (from tensorboard==2.3.0+computecanada->-r requirements.txt (line 5))
Collecting absl-py>=0.4 (from tensorboard==2.3.0+computecanada->-r requirements.txt (line 5))
Requirement already satisfied: requests<3,>=2.21.0 in /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages (from tensorboard==2.3.0+computecanada->-r requirements.txt (line 5)) (2.21.0)
Requirement already satisfied: setuptools>=41.0.0 in /localscratch/yinan.26042435.0/env/lib/python3.7/site-packages (from tensorboard==2.3.0+computecanada->-r requirements.txt (line 5)) (41.0.1)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /localscratch/yinan.26042435.0/env/lib/python3.7/site-packages (from tensorboard==2.3.0+computecanada->-r requirements.txt (line 5)) (0.33.4)
Collecting astunparse==1.6.3 (from tensorflow_gpu==2.3.0+computecanada->-r requirements.txt (line 7))
Collecting h5py<2.11.0,>=2.10.0 (from tensorflow_gpu==2.3.0+computecanada->-r requirements.txt (line 7))
Collecting google-pasta>=0.1.8 (from tensorflow_gpu==2.3.0+computecanada->-r requirements.txt (line 7))
Collecting opt-einsum>=2.3.2 (from tensorflow_gpu==2.3.0+computecanada->-r requirements.txt (line 7))
Collecting wrapt>=1.11.1 (from tensorflow_gpu==2.3.0+computecanada->-r requirements.txt (line 7))
Collecting termcolor>=1.1.0 (from tensorflow_gpu==2.3.0+computecanada->-r requirements.txt (line 7))
Collecting gast==0.3.3 (from tensorflow_gpu==2.3.0+computecanada->-r requirements.txt (line 7))
Requirement already satisfied: torch in /localscratch/yinan.26042435.0/env/lib/python3.7/site-packages (from torchtext==0.6.0->-r requirements.txt (line 10)) (1.9.1+computecanada)
Collecting sentencepiece (from torchtext==0.6.0->-r requirements.txt (line 10))
Collecting filelock (from transformers==2.5.1+computecanada->-r requirements.txt (line 11))
Collecting boto3 (from transformers==2.5.1+computecanada->-r requirements.txt (line 11))
Collecting sacremoses (from transformers==2.5.1+computecanada->-r requirements.txt (line 11))
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages (from click->nltk==3.5->-r requirements.txt (line 3)) (0.8)
Collecting cachetools<5.0,>=2.0.0 (from google-auth<2,>=1.6.3->tensorboard==2.3.0+computecanada->-r requirements.txt (line 5))
Collecting rsa<5,>=3.1.4; python_version >= "3.6" (from google-auth<2,>=1.6.3->tensorboard==2.3.0+computecanada->-r requirements.txt (line 5))
Collecting pyasn1-modules>=0.2.1 (from google-auth<2,>=1.6.3->tensorboard==2.3.0+computecanada->-r requirements.txt (line 5))
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard==2.3.0+computecanada->-r requirements.txt (line 5))
Requirement already satisfied: idna<2.9,>=2.5 in /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard==2.3.0+computecanada->-r requirements.txt (line 5)) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard==2.3.0+computecanada->-r requirements.txt (line 5)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard==2.3.0+computecanada->-r requirements.txt (line 5)) (2018.11.29)
Requirement already satisfied: typing-extensions in /localscratch/yinan.26042435.0/env/lib/python3.7/site-packages (from torch->torchtext==0.6.0->-r requirements.txt (line 10)) (4.0.0+computecanada)
Collecting jmespath<1.0.0,>=0.7.1 (from boto3->transformers==2.5.1+computecanada->-r requirements.txt (line 11))
Collecting botocore<1.24.0,>=1.23.46 (from boto3->transformers==2.5.1+computecanada->-r requirements.txt (line 11))
Collecting s3transfer<0.6.0,>=0.5.0 (from boto3->transformers==2.5.1+computecanada->-r requirements.txt (line 11))
Requirement already satisfied: zipp>=0.3.2 in /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->click->nltk==3.5->-r requirements.txt (line 3)) (0.3.3)
Requirement already satisfied: pyasn1>=0.1.3 in /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages (from rsa<5,>=3.1.4; python_version >= "3.6"->google-auth<2,>=1.6.3->tensorboard==2.3.0+computecanada->-r requirements.txt (line 5)) (0.4.3)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard==2.3.0+computecanada->-r requirements.txt (line 5))
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages (from botocore<1.24.0,>=1.23.46->boto3->transformers==2.5.1+computecanada->-r requirements.txt (line 11)) (2.7.5)
ERROR: requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.26.8+computecanada which is incompatible.
ERROR: markdown 3.3.6+computecanada has requirement importlib-metadata>=4.4; python_version < "3.10", but you'll have importlib-metadata 0.8 which is incompatible.
ERROR: pyasn1-modules 0.2.8+computecanada has requirement pyasn1<0.5.0,>=0.4.6, but you'll have pyasn1 0.4.3 which is incompatible.
ERROR: tensorflow-gpu 2.3.0+computecanada has requirement scipy==1.4.1, but you'll have scipy 1.2.0 which is incompatible.
Installing collected packages: Keras, Keras-Preprocessing, tqdm, joblib, regex, click, nltk, scikit-learn, markdown, grpcio, cachetools, rsa, pyasn1-modules, google-auth, oauthlib, requests-oauthlib, google-auth-oauthlib, werkzeug, protobuf, absl-py, tensorboard-plugin-wit, tensorboard, astunparse, h5py, google-pasta, opt-einsum, wrapt, tensorflow-estimator, termcolor, gast, tensorflow-gpu, tokenizers, sentencepiece, torchtext, filelock, jmespath, urllib3, botocore, s3transfer, boto3, sacremoses, transformers
  Found existing installation: urllib3 1.24.1
    Not uninstalling urllib3 at /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages, outside environment /localscratch/yinan.26042435.0/env
    Can't uninstall 'urllib3'. No files were found to uninstall.
Successfully installed Keras-2.7.0+computecanada Keras-Preprocessing-1.1.2+computecanada absl-py-1.0.0+computecanada astunparse-1.6.3+computecanada boto3-1.20.46+computecanada botocore-1.23.46+computecanada cachetools-4.2.4+computecanada click-8.0.3+computecanada filelock-3.3.2+computecanada gast-0.3.3+computecanada google-auth-1.35.0+computecanada google-auth-oauthlib-0.4.6+computecanada google-pasta-0.2.0+computecanada grpcio-1.38.0+computecanada h5py-2.10.0+computecanada jmespath-0.10.0+computecanada joblib-1.1.0+computecanada markdown-3.3.6+computecanada nltk-3.5+computecanada oauthlib-3.1.1+computecanada opt-einsum-3.3.0+computecanada protobuf-3.19.3+computecanada pyasn1-modules-0.2.8+computecanada regex-2020.11.13+computecanada requests-oauthlib-1.3.0+computecanada rsa-4.8+computecanada s3transfer-0.5.0+computecanada sacremoses-0.0.46+computecanada scikit-learn-0.22.1+computecanada sentencepiece-0.1.91+computecanada tensorboard-2.3.0+computecanada tensorboard-plugin-wit-1.7.0+computecanada tensorflow-estimator-2.3.0+computecanada tensorflow-gpu-2.3.0+computecanada termcolor-1.1.0+computecanada tokenizers-0.5.2+computecanada torchtext-0.6.0+computecanada tqdm-4.62.3+computecanada transformers-2.5.1+computecanada urllib3-1.26.8+computecanada werkzeug-2.0.2+computecanada wrapt-1.11.2+computecanada
Ignoring pip: markers 'python_version < "3"' don't match your environment
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/generic, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Collecting wandb
  Using cached https://files.pythonhosted.org/packages/05/39/d73e9a767184e0e1798255aed78e05ed4ebe988c0552f9abd36127dc2c53/wandb-0.12.10-py2.py3-none-any.whl
Collecting pathtools (from wandb)
Collecting sentry-sdk>=1.0.0 (from wandb)
  Using cached https://files.pythonhosted.org/packages/61/64/d588297b5c260d1ff38093e2b80d04f724bf23f9f10ecace6fd192529c69/sentry_sdk-1.5.4-py2.py3-none-any.whl
Collecting six>=1.13.0 (from wandb)
Requirement already satisfied, skipping upgrade: protobuf>=3.12.0 in /localscratch/yinan.26042435.0/env/lib/python3.7/site-packages (from wandb) (3.19.3+computecanada)
Collecting shortuuid>=0.5.0 (from wandb)
  Using cached https://files.pythonhosted.org/packages/22/1b/dda73524fc8dd5cd3b80adcc585a49b3f43f8889453d2ed96291b2fcc860/shortuuid-1.0.8-py3-none-any.whl
Requirement already satisfied, skipping upgrade: requests<3,>=2.0.0 in /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages (from wandb) (2.21.0)
Collecting PyYAML (from wandb)
Requirement already satisfied, skipping upgrade: Click!=8.0.0,>=7.0 in /localscratch/yinan.26042435.0/env/lib/python3.7/site-packages (from wandb) (8.0.3+computecanada)
Collecting docker-pycreds>=0.4.0 (from wandb)
Collecting promise<3,>=2.0 (from wandb)
Collecting GitPython>=1.0.0 (from wandb)
  Using cached https://files.pythonhosted.org/packages/ed/4e/441f12af8faed3b6efe95c4b9359943ee741d5a96a0fee0c9676bde0b7f4/GitPython-3.1.26-py3-none-any.whl
Collecting psutil>=5.0.0 (from wandb)
Collecting yaspin>=1.0.0 (from wandb)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages (from wandb) (2.7.5)
Requirement already satisfied, skipping upgrade: certifi in /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages (from sentry-sdk>=1.0.0->wandb) (2018.11.29)
Requirement already satisfied, skipping upgrade: urllib3>=1.10.0 in /localscratch/yinan.26042435.0/env/lib/python3.7/site-packages (from sentry-sdk>=1.0.0->wandb) (1.26.8+computecanada)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages (from requests<3,>=2.0.0->wandb) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages (from requests<3,>=2.0.0->wandb) (2.8)
Requirement already satisfied, skipping upgrade: importlib-metadata; python_version < "3.8" in /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages (from Click!=8.0.0,>=7.0->wandb) (0.8)
Collecting gitdb<5,>=4.0.1 (from GitPython>=1.0.0->wandb)
Requirement already satisfied, skipping upgrade: typing-extensions>=3.7.4.3; python_version < "3.8" in /localscratch/yinan.26042435.0/env/lib/python3.7/site-packages (from GitPython>=1.0.0->wandb) (4.0.0+computecanada)
Requirement already satisfied, skipping upgrade: termcolor<2.0.0,>=1.1.0 in /localscratch/yinan.26042435.0/env/lib/python3.7/site-packages (from yaspin>=1.0.0->wandb) (1.1.0+computecanada)
Requirement already satisfied, skipping upgrade: zipp>=0.3.2 in /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->Click!=8.0.0,>=7.0->wandb) (0.3.3)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->GitPython>=1.0.0->wandb)
ERROR: tensorflow-gpu 2.3.0+computecanada has requirement scipy==1.4.1, but you'll have scipy 1.2.0 which is incompatible.
Installing collected packages: pathtools, sentry-sdk, six, shortuuid, PyYAML, docker-pycreds, promise, smmap, gitdb, GitPython, psutil, yaspin, wandb
  Found existing installation: six 1.12.0
    Not uninstalling six at /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages, outside environment /localscratch/yinan.26042435.0/env
    Can't uninstall 'six'. No files were found to uninstall.
Successfully installed GitPython-3.1.26 PyYAML-5.3.1+computecanada docker-pycreds-0.4.0+computecanada gitdb-4.0.9+computecanada pathtools-0.1.2+computecanada promise-2.3+computecanada psutil-5.7.3+computecanada sentry-sdk-1.5.4 shortuuid-1.0.8 six-1.16.0+computecanada smmap-5.0.0+computecanada wandb-0.12.10 yaspin-2.1.0+computecanada
/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/localscratch/yinan.26042435.0/env/bin/wandb", line 10, in <module>
    sys.exit(cli())
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/cli/cli.py", line 86, in wrapper
    return func(*args, **kwargs)
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/cli/cli.py", line 235, in login
    wandb.login(relogin=relogin, key=key, anonymous=anon_mode, host=host, force=True)
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/sdk/wandb_login.py", line 76, in login
    configured = _login(**kwargs)
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/sdk/wandb_login.py", line 278, in _login
    wlogin.configure_api_key(key)
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/sdk/wandb_login.py", line 167, in configure_api_key
    apikey.write_key(self._settings, key)
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/sdk/lib/apikey.py", line 212, in write_key
    raise ValueError("API key must be 40 characters long, yours was %s" % len(key))
ValueError: API key must be 40 characters long, yours was 41
Starting Task
2022-02-02 20:53:12.974122: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
wandb: Currently logged in as: yinanazhou (use `wandb login --relogin` to force relogin)
2022-02-02 20:53:26.299669: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
wandb: Tracking run with wandb version 0.12.10
wandb: Syncing run upbeat-deluge-3
wandb: ⭐️ View project at https://wandb.ai/yinanazhou/xlnet8_512_bs_8_adamw_lr_1e05_es_0.01_20_fold_0
wandb: 🚀 View run at https://wandb.ai/yinanazhou/xlnet8_512_bs_8_adamw_lr_1e05_es_0.01_20_fold_0/runs/1ztmacm4
wandb: Run data is saved locally in /project/6002780/yinan/Thesis_MER_Lyrics/arch/lyric-emotion/wandb/run-20220202_205324-1ztmacm4
wandb: Run `wandb offline` to turn off syncing.
/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
wandb: Network error (ConnectionError), entering retry loop.
wandb: Network error (ConnectionError), entering retry loop.

wandb: Waiting for W&B process to finish, PID 91605... (success).
wandb: - 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: \ 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: | 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: / 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: - 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: \ 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: | 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: / 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: - 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: \ 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: | 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: / 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: - 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: \ 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb:                                                                                
wandb: Run history:
wandb:     F1_measure ▁▂▂▂▂▂▂▃▄▃▃▃▃▃▄▃▃▃▃▃▃▃▃▄▅▅▅▅▆▅▆████▇███▇
wandb:       accuracy ▁▃▃▃▃▃▃▃▄▄▃▃▃▄▄▃▃▄▄▃▄▄▃▄▅▅▅▅▆▅▅█▇██▇███▇
wandb:   e_F1_measure ▁▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▄███████████████████
wandb:     e_accuracy ▁▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▄███████████████████
wandb:         e_loss █▃▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:    e_precision ▁▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▄▆███████████████████
wandb:       e_recall ▁▂▂▂▂▂▂▂▂▂▃▂▂▂▂▃▃▃▃▃▄███████████████████
wandb:           loss █▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▁▁▂▁▂▁▁▁▁▁▁▁
wandb:      precision ▂▂▁▂▂▂▃▄▅▅▄▄▄▄▅▃▄▄▄▄▄▄▄▅▆▆▆▆▆▆▆████████▇
wandb:         recall ▁▃▃▃▃▃▃▃▄▄▃▃▃▃▄▃▃▄▄▃▄▄▃▄▅▅▅▅▆▅▅█▇██▇███▇
wandb: 
wandb: Run summary:
wandb:     F1_measure 79.37046
wandb:       accuracy 0.794
wandb:   e_F1_measure 92.31489
wandb:     e_accuracy 92.42902
wandb:         e_loss 0.06779
wandb:    e_precision 92.91527
wandb:       e_recall 92.01198
wandb:           loss 0.075
wandb:      precision 79.90989
wandb:         recall 79.32821
wandb: 
wandb: Synced 4 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Synced upbeat-deluge-3: https://wandb.ai/yinanazhou/xlnet8_512_bs_8_adamw_lr_1e05_es_0.01_20_fold_0/runs/1ztmacm4
wandb: Find logs at: ./wandb/run-20220202_205324-1ztmacm4/logs/debug.log
wandb: 

/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
wandb: Network error (ReadTimeout), entering retry loop.
wandb: ERROR Error while calling W&B API: Error 1062: Duplicate entry 'xlnet8_512_bs_8_adamw_lr_1e05_es_0.01_20_fold_1-159948' for key 'ix_projects_name_entity_id' (<Response [409]>)
Thread SenderThread:
Traceback (most recent call last):
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1296, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 146, in execute
    six.reraise(*sys.exc_info())
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/sdk/internal/internal_util.py", line 54, in run
    self._run()
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/sdk/internal/internal_util.py", line 105, in _run
    self._process(record)
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/sdk/internal/internal.py", line 305, in _process
    self._sm.send(record)
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/sdk/internal/sender.py", line 237, in send
    send_handler(record)
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/sdk/internal/sender.py", line 692, in send_run
    self._init_run(run, config_value_dict)
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/sdk/internal/sender.py", line 730, in _init_run
    commit=run.git.last_commit or None,
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    raise CommError(err.response, err)
wandb.errors.CommError: <Response [409]>
wandb: ERROR Internal wandb error: file data was not synced
wandb: ERROR Error communicating with wandb process
wandb: ERROR try: wandb.init(settings=wandb.Settings(start_method='fork'))
wandb: ERROR or:  wandb.init(settings=wandb.Settings(start_method='thread'))
wandb: ERROR For more info see: https://docs.wandb.ai/library/init#init-start-error
Problem at: xlnet_cv.py 286 <module>
wandb: ERROR Error communicating with wandb process
wandb: ERROR try: wandb.init(settings=wandb.Settings(start_method='fork'))
wandb: ERROR or:  wandb.init(settings=wandb.Settings(start_method='thread'))
wandb: ERROR For more info see: https://docs.wandb.ai/library/init#init-start-error
Traceback (most recent call last):
  File "xlnet_cv.py", line 286, in <module>
    wandb.init(project=wandb_pj, entity="yinanazhou")
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 951, in init
    run = wi.init()
  File "/localscratch/yinan.26042435.0/env/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 616, in init
    raise UsageError(error_message)
wandb.errors.UsageError: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
